version: 0.2

phases:
 install: 
  commands:
   - echo "===============Entered the install phase...========================"
   # - sudo yum -y update
   - gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
   - \curl -sSL https://get.rvm.io | bash
   - rvm install ruby
   - gem install bundler
   - sudo yum install -y gcc-c++ make
   - curl -sL https://rpm.nodesource.com/setup_6.x | sudo -E bash -
   - yum install nodejs

 build:
  commands:
   - echo "=================Entered the build phase...=========================="
   - bundle install 
 post_build:
  commands:
   - echo "===============Entered the post_build phase...==============="
   - echo Build completed on `date`

artifacts:
 files:
  - '**/*' 
